/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ReportRouteImport } from './routes/report'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PressRouteImport } from './routes/press'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ListingsRouteImport } from './routes/listings'
import { Route as HelpRouteImport } from './routes/help'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PropertyIdRouteImport } from './routes/property.$id'
import { Route as DashboardTenantRouteImport } from './routes/dashboard.tenant'
import { Route as DashboardLandlordRouteImport } from './routes/dashboard.landlord'
import { Route as DashboardAdminRouteImport } from './routes/dashboard.admin'
import { Route as DashboardTenantIndexRouteImport } from './routes/dashboard.tenant.index'
import { Route as DashboardLandlordIndexRouteImport } from './routes/dashboard.landlord.index'
import { Route as DashboardAdminIndexRouteImport } from './routes/dashboard.admin.index'
import { Route as DashboardTenantVisitsRouteImport } from './routes/dashboard.tenant.visits'
import { Route as DashboardTenantSearchRouteImport } from './routes/dashboard.tenant.search'
import { Route as DashboardTenantReviewsRouteImport } from './routes/dashboard.tenant.reviews'
import { Route as DashboardTenantRentRouteImport } from './routes/dashboard.tenant.rent'
import { Route as DashboardTenantProfileRouteImport } from './routes/dashboard.tenant.profile'
import { Route as DashboardTenantNotificationsRouteImport } from './routes/dashboard.tenant.notifications'
import { Route as DashboardTenantMessagesRouteImport } from './routes/dashboard.tenant.messages'
import { Route as DashboardTenantMapRouteImport } from './routes/dashboard.tenant.map'
import { Route as DashboardTenantFeedRouteImport } from './routes/dashboard.tenant.feed'
import { Route as DashboardTenantFavoritesRouteImport } from './routes/dashboard.tenant.favorites'
import { Route as DashboardTenantCompareRouteImport } from './routes/dashboard.tenant.compare'
import { Route as DashboardLandlordVisitsRouteImport } from './routes/dashboard.landlord.visits'
import { Route as DashboardLandlordTransactionsRouteImport } from './routes/dashboard.landlord.transactions'
import { Route as DashboardLandlordTenantsRouteImport } from './routes/dashboard.landlord.tenants'
import { Route as DashboardLandlordSettingsRouteImport } from './routes/dashboard.landlord.settings'
import { Route as DashboardLandlordReviewsRouteImport } from './routes/dashboard.landlord.reviews'
import { Route as DashboardLandlordPropertiesRouteImport } from './routes/dashboard.landlord.properties'
import { Route as DashboardLandlordMessagesRouteImport } from './routes/dashboard.landlord.messages'
import { Route as DashboardLandlordAnalyticsRouteImport } from './routes/dashboard.landlord.analytics'
import { Route as DashboardLandlordAddPropertyRouteImport } from './routes/dashboard.landlord.add-property'
import { Route as DashboardAdminVerificationsRouteImport } from './routes/dashboard.admin.verifications'
import { Route as DashboardAdminUsersRouteImport } from './routes/dashboard.admin.users'
import { Route as DashboardAdminTransactionsRouteImport } from './routes/dashboard.admin.transactions'
import { Route as DashboardAdminTenantsRouteImport } from './routes/dashboard.admin.tenants'
import { Route as DashboardAdminSettingsRouteImport } from './routes/dashboard.admin.settings'
import { Route as DashboardAdminReviewsRouteImport } from './routes/dashboard.admin.reviews'
import { Route as DashboardAdminReportsRouteImport } from './routes/dashboard.admin.reports'
import { Route as DashboardAdminPropertiesRouteImport } from './routes/dashboard.admin.properties'
import { Route as DashboardAdminNotificationsRouteImport } from './routes/dashboard.admin.notifications'
import { Route as DashboardAdminLandlordsRouteImport } from './routes/dashboard.admin.landlords'
import { Route as DashboardAdminAnalyticsRouteImport } from './routes/dashboard.admin.analytics'

const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportRoute = ReportRouteImport.update({
  id: '/report',
  path: '/report',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PressRoute = PressRouteImport.update({
  id: '/press',
  path: '/press',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ListingsRoute = ListingsRouteImport.update({
  id: '/listings',
  path: '/listings',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PropertyIdRoute = PropertyIdRouteImport.update({
  id: '/property/$id',
  path: '/property/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantRoute = DashboardTenantRouteImport.update({
  id: '/dashboard/tenant',
  path: '/dashboard/tenant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardLandlordRoute = DashboardLandlordRouteImport.update({
  id: '/dashboard/landlord',
  path: '/dashboard/landlord',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAdminRoute = DashboardAdminRouteImport.update({
  id: '/dashboard/admin',
  path: '/dashboard/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardTenantIndexRoute = DashboardTenantIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardTenantRoute,
} as any)
const DashboardLandlordIndexRoute = DashboardLandlordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardLandlordRoute,
} as any)
const DashboardAdminIndexRoute = DashboardAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardTenantVisitsRoute = DashboardTenantVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => DashboardTenantRoute,
} as any)
const DashboardTenantSearchRoute = DashboardTenantSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => DashboardTenantRoute,
} as any)
const DashboardTenantReviewsRoute = DashboardTenantReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardTenantRoute,
} as any)
const DashboardTenantRentRoute = DashboardTenantRentRouteImport.update({
  id: '/rent',
  path: '/rent',
  getParentRoute: () => DashboardTenantRoute,
} as any)
const DashboardTenantProfileRoute = DashboardTenantProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => DashboardTenantRoute,
} as any)
const DashboardTenantNotificationsRoute =
  DashboardTenantNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardTenantRoute,
  } as any)
const DashboardTenantMessagesRoute = DashboardTenantMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => DashboardTenantRoute,
} as any)
const DashboardTenantMapRoute = DashboardTenantMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => DashboardTenantRoute,
} as any)
const DashboardTenantFeedRoute = DashboardTenantFeedRouteImport.update({
  id: '/feed',
  path: '/feed',
  getParentRoute: () => DashboardTenantRoute,
} as any)
const DashboardTenantFavoritesRoute =
  DashboardTenantFavoritesRouteImport.update({
    id: '/favorites',
    path: '/favorites',
    getParentRoute: () => DashboardTenantRoute,
  } as any)
const DashboardTenantCompareRoute = DashboardTenantCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => DashboardTenantRoute,
} as any)
const DashboardLandlordVisitsRoute = DashboardLandlordVisitsRouteImport.update({
  id: '/visits',
  path: '/visits',
  getParentRoute: () => DashboardLandlordRoute,
} as any)
const DashboardLandlordTransactionsRoute =
  DashboardLandlordTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => DashboardLandlordRoute,
  } as any)
const DashboardLandlordTenantsRoute =
  DashboardLandlordTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => DashboardLandlordRoute,
  } as any)
const DashboardLandlordSettingsRoute =
  DashboardLandlordSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => DashboardLandlordRoute,
  } as any)
const DashboardLandlordReviewsRoute =
  DashboardLandlordReviewsRouteImport.update({
    id: '/reviews',
    path: '/reviews',
    getParentRoute: () => DashboardLandlordRoute,
  } as any)
const DashboardLandlordPropertiesRoute =
  DashboardLandlordPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => DashboardLandlordRoute,
  } as any)
const DashboardLandlordMessagesRoute =
  DashboardLandlordMessagesRouteImport.update({
    id: '/messages',
    path: '/messages',
    getParentRoute: () => DashboardLandlordRoute,
  } as any)
const DashboardLandlordAnalyticsRoute =
  DashboardLandlordAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => DashboardLandlordRoute,
  } as any)
const DashboardLandlordAddPropertyRoute =
  DashboardLandlordAddPropertyRouteImport.update({
    id: '/add-property',
    path: '/add-property',
    getParentRoute: () => DashboardLandlordRoute,
  } as any)
const DashboardAdminVerificationsRoute =
  DashboardAdminVerificationsRouteImport.update({
    id: '/verifications',
    path: '/verifications',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminUsersRoute = DashboardAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminTransactionsRoute =
  DashboardAdminTransactionsRouteImport.update({
    id: '/transactions',
    path: '/transactions',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminTenantsRoute = DashboardAdminTenantsRouteImport.update({
  id: '/tenants',
  path: '/tenants',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminSettingsRoute = DashboardAdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminReviewsRoute = DashboardAdminReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminReportsRoute = DashboardAdminReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminPropertiesRoute =
  DashboardAdminPropertiesRouteImport.update({
    id: '/properties',
    path: '/properties',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminNotificationsRoute =
  DashboardAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => DashboardAdminRoute,
  } as any)
const DashboardAdminLandlordsRoute = DashboardAdminLandlordsRouteImport.update({
  id: '/landlords',
  path: '/landlords',
  getParentRoute: () => DashboardAdminRoute,
} as any)
const DashboardAdminAnalyticsRoute = DashboardAdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => DashboardAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/landlord': typeof DashboardLandlordRouteWithChildren
  '/dashboard/tenant': typeof DashboardTenantRouteWithChildren
  '/property/$id': typeof PropertyIdRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/landlords': typeof DashboardAdminLandlordsRoute
  '/dashboard/admin/notifications': typeof DashboardAdminNotificationsRoute
  '/dashboard/admin/properties': typeof DashboardAdminPropertiesRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/reviews': typeof DashboardAdminReviewsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/tenants': typeof DashboardAdminTenantsRoute
  '/dashboard/admin/transactions': typeof DashboardAdminTransactionsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/verifications': typeof DashboardAdminVerificationsRoute
  '/dashboard/landlord/add-property': typeof DashboardLandlordAddPropertyRoute
  '/dashboard/landlord/analytics': typeof DashboardLandlordAnalyticsRoute
  '/dashboard/landlord/messages': typeof DashboardLandlordMessagesRoute
  '/dashboard/landlord/properties': typeof DashboardLandlordPropertiesRoute
  '/dashboard/landlord/reviews': typeof DashboardLandlordReviewsRoute
  '/dashboard/landlord/settings': typeof DashboardLandlordSettingsRoute
  '/dashboard/landlord/tenants': typeof DashboardLandlordTenantsRoute
  '/dashboard/landlord/transactions': typeof DashboardLandlordTransactionsRoute
  '/dashboard/landlord/visits': typeof DashboardLandlordVisitsRoute
  '/dashboard/tenant/compare': typeof DashboardTenantCompareRoute
  '/dashboard/tenant/favorites': typeof DashboardTenantFavoritesRoute
  '/dashboard/tenant/feed': typeof DashboardTenantFeedRoute
  '/dashboard/tenant/map': typeof DashboardTenantMapRoute
  '/dashboard/tenant/messages': typeof DashboardTenantMessagesRoute
  '/dashboard/tenant/notifications': typeof DashboardTenantNotificationsRoute
  '/dashboard/tenant/profile': typeof DashboardTenantProfileRoute
  '/dashboard/tenant/rent': typeof DashboardTenantRentRoute
  '/dashboard/tenant/reviews': typeof DashboardTenantReviewsRoute
  '/dashboard/tenant/search': typeof DashboardTenantSearchRoute
  '/dashboard/tenant/visits': typeof DashboardTenantVisitsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/landlord/': typeof DashboardLandlordIndexRoute
  '/dashboard/tenant/': typeof DashboardTenantIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/property/$id': typeof PropertyIdRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/landlords': typeof DashboardAdminLandlordsRoute
  '/dashboard/admin/notifications': typeof DashboardAdminNotificationsRoute
  '/dashboard/admin/properties': typeof DashboardAdminPropertiesRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/reviews': typeof DashboardAdminReviewsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/tenants': typeof DashboardAdminTenantsRoute
  '/dashboard/admin/transactions': typeof DashboardAdminTransactionsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/verifications': typeof DashboardAdminVerificationsRoute
  '/dashboard/landlord/add-property': typeof DashboardLandlordAddPropertyRoute
  '/dashboard/landlord/analytics': typeof DashboardLandlordAnalyticsRoute
  '/dashboard/landlord/messages': typeof DashboardLandlordMessagesRoute
  '/dashboard/landlord/properties': typeof DashboardLandlordPropertiesRoute
  '/dashboard/landlord/reviews': typeof DashboardLandlordReviewsRoute
  '/dashboard/landlord/settings': typeof DashboardLandlordSettingsRoute
  '/dashboard/landlord/tenants': typeof DashboardLandlordTenantsRoute
  '/dashboard/landlord/transactions': typeof DashboardLandlordTransactionsRoute
  '/dashboard/landlord/visits': typeof DashboardLandlordVisitsRoute
  '/dashboard/tenant/compare': typeof DashboardTenantCompareRoute
  '/dashboard/tenant/favorites': typeof DashboardTenantFavoritesRoute
  '/dashboard/tenant/feed': typeof DashboardTenantFeedRoute
  '/dashboard/tenant/map': typeof DashboardTenantMapRoute
  '/dashboard/tenant/messages': typeof DashboardTenantMessagesRoute
  '/dashboard/tenant/notifications': typeof DashboardTenantNotificationsRoute
  '/dashboard/tenant/profile': typeof DashboardTenantProfileRoute
  '/dashboard/tenant/rent': typeof DashboardTenantRentRoute
  '/dashboard/tenant/reviews': typeof DashboardTenantReviewsRoute
  '/dashboard/tenant/search': typeof DashboardTenantSearchRoute
  '/dashboard/tenant/visits': typeof DashboardTenantVisitsRoute
  '/dashboard/admin': typeof DashboardAdminIndexRoute
  '/dashboard/landlord': typeof DashboardLandlordIndexRoute
  '/dashboard/tenant': typeof DashboardTenantIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/help': typeof HelpRoute
  '/listings': typeof ListingsRoute
  '/login': typeof LoginRoute
  '/press': typeof PressRoute
  '/privacy': typeof PrivacyRoute
  '/report': typeof ReportRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/dashboard/admin': typeof DashboardAdminRouteWithChildren
  '/dashboard/landlord': typeof DashboardLandlordRouteWithChildren
  '/dashboard/tenant': typeof DashboardTenantRouteWithChildren
  '/property/$id': typeof PropertyIdRoute
  '/dashboard/admin/analytics': typeof DashboardAdminAnalyticsRoute
  '/dashboard/admin/landlords': typeof DashboardAdminLandlordsRoute
  '/dashboard/admin/notifications': typeof DashboardAdminNotificationsRoute
  '/dashboard/admin/properties': typeof DashboardAdminPropertiesRoute
  '/dashboard/admin/reports': typeof DashboardAdminReportsRoute
  '/dashboard/admin/reviews': typeof DashboardAdminReviewsRoute
  '/dashboard/admin/settings': typeof DashboardAdminSettingsRoute
  '/dashboard/admin/tenants': typeof DashboardAdminTenantsRoute
  '/dashboard/admin/transactions': typeof DashboardAdminTransactionsRoute
  '/dashboard/admin/users': typeof DashboardAdminUsersRoute
  '/dashboard/admin/verifications': typeof DashboardAdminVerificationsRoute
  '/dashboard/landlord/add-property': typeof DashboardLandlordAddPropertyRoute
  '/dashboard/landlord/analytics': typeof DashboardLandlordAnalyticsRoute
  '/dashboard/landlord/messages': typeof DashboardLandlordMessagesRoute
  '/dashboard/landlord/properties': typeof DashboardLandlordPropertiesRoute
  '/dashboard/landlord/reviews': typeof DashboardLandlordReviewsRoute
  '/dashboard/landlord/settings': typeof DashboardLandlordSettingsRoute
  '/dashboard/landlord/tenants': typeof DashboardLandlordTenantsRoute
  '/dashboard/landlord/transactions': typeof DashboardLandlordTransactionsRoute
  '/dashboard/landlord/visits': typeof DashboardLandlordVisitsRoute
  '/dashboard/tenant/compare': typeof DashboardTenantCompareRoute
  '/dashboard/tenant/favorites': typeof DashboardTenantFavoritesRoute
  '/dashboard/tenant/feed': typeof DashboardTenantFeedRoute
  '/dashboard/tenant/map': typeof DashboardTenantMapRoute
  '/dashboard/tenant/messages': typeof DashboardTenantMessagesRoute
  '/dashboard/tenant/notifications': typeof DashboardTenantNotificationsRoute
  '/dashboard/tenant/profile': typeof DashboardTenantProfileRoute
  '/dashboard/tenant/rent': typeof DashboardTenantRentRoute
  '/dashboard/tenant/reviews': typeof DashboardTenantReviewsRoute
  '/dashboard/tenant/search': typeof DashboardTenantSearchRoute
  '/dashboard/tenant/visits': typeof DashboardTenantVisitsRoute
  '/dashboard/admin/': typeof DashboardAdminIndexRoute
  '/dashboard/landlord/': typeof DashboardLandlordIndexRoute
  '/dashboard/tenant/': typeof DashboardTenantIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/help'
    | '/listings'
    | '/login'
    | '/press'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard/admin'
    | '/dashboard/landlord'
    | '/dashboard/tenant'
    | '/property/$id'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/landlords'
    | '/dashboard/admin/notifications'
    | '/dashboard/admin/properties'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/reviews'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/tenants'
    | '/dashboard/admin/transactions'
    | '/dashboard/admin/users'
    | '/dashboard/admin/verifications'
    | '/dashboard/landlord/add-property'
    | '/dashboard/landlord/analytics'
    | '/dashboard/landlord/messages'
    | '/dashboard/landlord/properties'
    | '/dashboard/landlord/reviews'
    | '/dashboard/landlord/settings'
    | '/dashboard/landlord/tenants'
    | '/dashboard/landlord/transactions'
    | '/dashboard/landlord/visits'
    | '/dashboard/tenant/compare'
    | '/dashboard/tenant/favorites'
    | '/dashboard/tenant/feed'
    | '/dashboard/tenant/map'
    | '/dashboard/tenant/messages'
    | '/dashboard/tenant/notifications'
    | '/dashboard/tenant/profile'
    | '/dashboard/tenant/rent'
    | '/dashboard/tenant/reviews'
    | '/dashboard/tenant/search'
    | '/dashboard/tenant/visits'
    | '/dashboard/admin/'
    | '/dashboard/landlord/'
    | '/dashboard/tenant/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/help'
    | '/listings'
    | '/login'
    | '/press'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/property/$id'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/landlords'
    | '/dashboard/admin/notifications'
    | '/dashboard/admin/properties'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/reviews'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/tenants'
    | '/dashboard/admin/transactions'
    | '/dashboard/admin/users'
    | '/dashboard/admin/verifications'
    | '/dashboard/landlord/add-property'
    | '/dashboard/landlord/analytics'
    | '/dashboard/landlord/messages'
    | '/dashboard/landlord/properties'
    | '/dashboard/landlord/reviews'
    | '/dashboard/landlord/settings'
    | '/dashboard/landlord/tenants'
    | '/dashboard/landlord/transactions'
    | '/dashboard/landlord/visits'
    | '/dashboard/tenant/compare'
    | '/dashboard/tenant/favorites'
    | '/dashboard/tenant/feed'
    | '/dashboard/tenant/map'
    | '/dashboard/tenant/messages'
    | '/dashboard/tenant/notifications'
    | '/dashboard/tenant/profile'
    | '/dashboard/tenant/rent'
    | '/dashboard/tenant/reviews'
    | '/dashboard/tenant/search'
    | '/dashboard/tenant/visits'
    | '/dashboard/admin'
    | '/dashboard/landlord'
    | '/dashboard/tenant'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/forgot-password'
    | '/help'
    | '/listings'
    | '/login'
    | '/press'
    | '/privacy'
    | '/report'
    | '/reset-password'
    | '/signup'
    | '/terms'
    | '/dashboard/admin'
    | '/dashboard/landlord'
    | '/dashboard/tenant'
    | '/property/$id'
    | '/dashboard/admin/analytics'
    | '/dashboard/admin/landlords'
    | '/dashboard/admin/notifications'
    | '/dashboard/admin/properties'
    | '/dashboard/admin/reports'
    | '/dashboard/admin/reviews'
    | '/dashboard/admin/settings'
    | '/dashboard/admin/tenants'
    | '/dashboard/admin/transactions'
    | '/dashboard/admin/users'
    | '/dashboard/admin/verifications'
    | '/dashboard/landlord/add-property'
    | '/dashboard/landlord/analytics'
    | '/dashboard/landlord/messages'
    | '/dashboard/landlord/properties'
    | '/dashboard/landlord/reviews'
    | '/dashboard/landlord/settings'
    | '/dashboard/landlord/tenants'
    | '/dashboard/landlord/transactions'
    | '/dashboard/landlord/visits'
    | '/dashboard/tenant/compare'
    | '/dashboard/tenant/favorites'
    | '/dashboard/tenant/feed'
    | '/dashboard/tenant/map'
    | '/dashboard/tenant/messages'
    | '/dashboard/tenant/notifications'
    | '/dashboard/tenant/profile'
    | '/dashboard/tenant/rent'
    | '/dashboard/tenant/reviews'
    | '/dashboard/tenant/search'
    | '/dashboard/tenant/visits'
    | '/dashboard/admin/'
    | '/dashboard/landlord/'
    | '/dashboard/tenant/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  HelpRoute: typeof HelpRoute
  ListingsRoute: typeof ListingsRoute
  LoginRoute: typeof LoginRoute
  PressRoute: typeof PressRoute
  PrivacyRoute: typeof PrivacyRoute
  ReportRoute: typeof ReportRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  DashboardAdminRoute: typeof DashboardAdminRouteWithChildren
  DashboardLandlordRoute: typeof DashboardLandlordRouteWithChildren
  DashboardTenantRoute: typeof DashboardTenantRouteWithChildren
  PropertyIdRoute: typeof PropertyIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report': {
      id: '/report'
      path: '/report'
      fullPath: '/report'
      preLoaderRoute: typeof ReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/press': {
      id: '/press'
      path: '/press'
      fullPath: '/press'
      preLoaderRoute: typeof PressRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/listings': {
      id: '/listings'
      path: '/listings'
      fullPath: '/listings'
      preLoaderRoute: typeof ListingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/property/$id': {
      id: '/property/$id'
      path: '/property/$id'
      fullPath: '/property/$id'
      preLoaderRoute: typeof PropertyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenant': {
      id: '/dashboard/tenant'
      path: '/dashboard/tenant'
      fullPath: '/dashboard/tenant'
      preLoaderRoute: typeof DashboardTenantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/landlord': {
      id: '/dashboard/landlord'
      path: '/dashboard/landlord'
      fullPath: '/dashboard/landlord'
      preLoaderRoute: typeof DashboardLandlordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/admin': {
      id: '/dashboard/admin'
      path: '/dashboard/admin'
      fullPath: '/dashboard/admin'
      preLoaderRoute: typeof DashboardAdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/tenant/': {
      id: '/dashboard/tenant/'
      path: '/'
      fullPath: '/dashboard/tenant/'
      preLoaderRoute: typeof DashboardTenantIndexRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/landlord/': {
      id: '/dashboard/landlord/'
      path: '/'
      fullPath: '/dashboard/landlord/'
      preLoaderRoute: typeof DashboardLandlordIndexRouteImport
      parentRoute: typeof DashboardLandlordRoute
    }
    '/dashboard/admin/': {
      id: '/dashboard/admin/'
      path: '/'
      fullPath: '/dashboard/admin/'
      preLoaderRoute: typeof DashboardAdminIndexRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/tenant/visits': {
      id: '/dashboard/tenant/visits'
      path: '/visits'
      fullPath: '/dashboard/tenant/visits'
      preLoaderRoute: typeof DashboardTenantVisitsRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/tenant/search': {
      id: '/dashboard/tenant/search'
      path: '/search'
      fullPath: '/dashboard/tenant/search'
      preLoaderRoute: typeof DashboardTenantSearchRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/tenant/reviews': {
      id: '/dashboard/tenant/reviews'
      path: '/reviews'
      fullPath: '/dashboard/tenant/reviews'
      preLoaderRoute: typeof DashboardTenantReviewsRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/tenant/rent': {
      id: '/dashboard/tenant/rent'
      path: '/rent'
      fullPath: '/dashboard/tenant/rent'
      preLoaderRoute: typeof DashboardTenantRentRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/tenant/profile': {
      id: '/dashboard/tenant/profile'
      path: '/profile'
      fullPath: '/dashboard/tenant/profile'
      preLoaderRoute: typeof DashboardTenantProfileRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/tenant/notifications': {
      id: '/dashboard/tenant/notifications'
      path: '/notifications'
      fullPath: '/dashboard/tenant/notifications'
      preLoaderRoute: typeof DashboardTenantNotificationsRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/tenant/messages': {
      id: '/dashboard/tenant/messages'
      path: '/messages'
      fullPath: '/dashboard/tenant/messages'
      preLoaderRoute: typeof DashboardTenantMessagesRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/tenant/map': {
      id: '/dashboard/tenant/map'
      path: '/map'
      fullPath: '/dashboard/tenant/map'
      preLoaderRoute: typeof DashboardTenantMapRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/tenant/feed': {
      id: '/dashboard/tenant/feed'
      path: '/feed'
      fullPath: '/dashboard/tenant/feed'
      preLoaderRoute: typeof DashboardTenantFeedRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/tenant/favorites': {
      id: '/dashboard/tenant/favorites'
      path: '/favorites'
      fullPath: '/dashboard/tenant/favorites'
      preLoaderRoute: typeof DashboardTenantFavoritesRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/tenant/compare': {
      id: '/dashboard/tenant/compare'
      path: '/compare'
      fullPath: '/dashboard/tenant/compare'
      preLoaderRoute: typeof DashboardTenantCompareRouteImport
      parentRoute: typeof DashboardTenantRoute
    }
    '/dashboard/landlord/visits': {
      id: '/dashboard/landlord/visits'
      path: '/visits'
      fullPath: '/dashboard/landlord/visits'
      preLoaderRoute: typeof DashboardLandlordVisitsRouteImport
      parentRoute: typeof DashboardLandlordRoute
    }
    '/dashboard/landlord/transactions': {
      id: '/dashboard/landlord/transactions'
      path: '/transactions'
      fullPath: '/dashboard/landlord/transactions'
      preLoaderRoute: typeof DashboardLandlordTransactionsRouteImport
      parentRoute: typeof DashboardLandlordRoute
    }
    '/dashboard/landlord/tenants': {
      id: '/dashboard/landlord/tenants'
      path: '/tenants'
      fullPath: '/dashboard/landlord/tenants'
      preLoaderRoute: typeof DashboardLandlordTenantsRouteImport
      parentRoute: typeof DashboardLandlordRoute
    }
    '/dashboard/landlord/settings': {
      id: '/dashboard/landlord/settings'
      path: '/settings'
      fullPath: '/dashboard/landlord/settings'
      preLoaderRoute: typeof DashboardLandlordSettingsRouteImport
      parentRoute: typeof DashboardLandlordRoute
    }
    '/dashboard/landlord/reviews': {
      id: '/dashboard/landlord/reviews'
      path: '/reviews'
      fullPath: '/dashboard/landlord/reviews'
      preLoaderRoute: typeof DashboardLandlordReviewsRouteImport
      parentRoute: typeof DashboardLandlordRoute
    }
    '/dashboard/landlord/properties': {
      id: '/dashboard/landlord/properties'
      path: '/properties'
      fullPath: '/dashboard/landlord/properties'
      preLoaderRoute: typeof DashboardLandlordPropertiesRouteImport
      parentRoute: typeof DashboardLandlordRoute
    }
    '/dashboard/landlord/messages': {
      id: '/dashboard/landlord/messages'
      path: '/messages'
      fullPath: '/dashboard/landlord/messages'
      preLoaderRoute: typeof DashboardLandlordMessagesRouteImport
      parentRoute: typeof DashboardLandlordRoute
    }
    '/dashboard/landlord/analytics': {
      id: '/dashboard/landlord/analytics'
      path: '/analytics'
      fullPath: '/dashboard/landlord/analytics'
      preLoaderRoute: typeof DashboardLandlordAnalyticsRouteImport
      parentRoute: typeof DashboardLandlordRoute
    }
    '/dashboard/landlord/add-property': {
      id: '/dashboard/landlord/add-property'
      path: '/add-property'
      fullPath: '/dashboard/landlord/add-property'
      preLoaderRoute: typeof DashboardLandlordAddPropertyRouteImport
      parentRoute: typeof DashboardLandlordRoute
    }
    '/dashboard/admin/verifications': {
      id: '/dashboard/admin/verifications'
      path: '/verifications'
      fullPath: '/dashboard/admin/verifications'
      preLoaderRoute: typeof DashboardAdminVerificationsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/users': {
      id: '/dashboard/admin/users'
      path: '/users'
      fullPath: '/dashboard/admin/users'
      preLoaderRoute: typeof DashboardAdminUsersRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/transactions': {
      id: '/dashboard/admin/transactions'
      path: '/transactions'
      fullPath: '/dashboard/admin/transactions'
      preLoaderRoute: typeof DashboardAdminTransactionsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/tenants': {
      id: '/dashboard/admin/tenants'
      path: '/tenants'
      fullPath: '/dashboard/admin/tenants'
      preLoaderRoute: typeof DashboardAdminTenantsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/settings': {
      id: '/dashboard/admin/settings'
      path: '/settings'
      fullPath: '/dashboard/admin/settings'
      preLoaderRoute: typeof DashboardAdminSettingsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/reviews': {
      id: '/dashboard/admin/reviews'
      path: '/reviews'
      fullPath: '/dashboard/admin/reviews'
      preLoaderRoute: typeof DashboardAdminReviewsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/reports': {
      id: '/dashboard/admin/reports'
      path: '/reports'
      fullPath: '/dashboard/admin/reports'
      preLoaderRoute: typeof DashboardAdminReportsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/properties': {
      id: '/dashboard/admin/properties'
      path: '/properties'
      fullPath: '/dashboard/admin/properties'
      preLoaderRoute: typeof DashboardAdminPropertiesRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/notifications': {
      id: '/dashboard/admin/notifications'
      path: '/notifications'
      fullPath: '/dashboard/admin/notifications'
      preLoaderRoute: typeof DashboardAdminNotificationsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/landlords': {
      id: '/dashboard/admin/landlords'
      path: '/landlords'
      fullPath: '/dashboard/admin/landlords'
      preLoaderRoute: typeof DashboardAdminLandlordsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
    '/dashboard/admin/analytics': {
      id: '/dashboard/admin/analytics'
      path: '/analytics'
      fullPath: '/dashboard/admin/analytics'
      preLoaderRoute: typeof DashboardAdminAnalyticsRouteImport
      parentRoute: typeof DashboardAdminRoute
    }
  }
}

interface DashboardAdminRouteChildren {
  DashboardAdminAnalyticsRoute: typeof DashboardAdminAnalyticsRoute
  DashboardAdminLandlordsRoute: typeof DashboardAdminLandlordsRoute
  DashboardAdminNotificationsRoute: typeof DashboardAdminNotificationsRoute
  DashboardAdminPropertiesRoute: typeof DashboardAdminPropertiesRoute
  DashboardAdminReportsRoute: typeof DashboardAdminReportsRoute
  DashboardAdminReviewsRoute: typeof DashboardAdminReviewsRoute
  DashboardAdminSettingsRoute: typeof DashboardAdminSettingsRoute
  DashboardAdminTenantsRoute: typeof DashboardAdminTenantsRoute
  DashboardAdminTransactionsRoute: typeof DashboardAdminTransactionsRoute
  DashboardAdminUsersRoute: typeof DashboardAdminUsersRoute
  DashboardAdminVerificationsRoute: typeof DashboardAdminVerificationsRoute
  DashboardAdminIndexRoute: typeof DashboardAdminIndexRoute
}

const DashboardAdminRouteChildren: DashboardAdminRouteChildren = {
  DashboardAdminAnalyticsRoute: DashboardAdminAnalyticsRoute,
  DashboardAdminLandlordsRoute: DashboardAdminLandlordsRoute,
  DashboardAdminNotificationsRoute: DashboardAdminNotificationsRoute,
  DashboardAdminPropertiesRoute: DashboardAdminPropertiesRoute,
  DashboardAdminReportsRoute: DashboardAdminReportsRoute,
  DashboardAdminReviewsRoute: DashboardAdminReviewsRoute,
  DashboardAdminSettingsRoute: DashboardAdminSettingsRoute,
  DashboardAdminTenantsRoute: DashboardAdminTenantsRoute,
  DashboardAdminTransactionsRoute: DashboardAdminTransactionsRoute,
  DashboardAdminUsersRoute: DashboardAdminUsersRoute,
  DashboardAdminVerificationsRoute: DashboardAdminVerificationsRoute,
  DashboardAdminIndexRoute: DashboardAdminIndexRoute,
}

const DashboardAdminRouteWithChildren = DashboardAdminRoute._addFileChildren(
  DashboardAdminRouteChildren,
)

interface DashboardLandlordRouteChildren {
  DashboardLandlordAddPropertyRoute: typeof DashboardLandlordAddPropertyRoute
  DashboardLandlordAnalyticsRoute: typeof DashboardLandlordAnalyticsRoute
  DashboardLandlordMessagesRoute: typeof DashboardLandlordMessagesRoute
  DashboardLandlordPropertiesRoute: typeof DashboardLandlordPropertiesRoute
  DashboardLandlordReviewsRoute: typeof DashboardLandlordReviewsRoute
  DashboardLandlordSettingsRoute: typeof DashboardLandlordSettingsRoute
  DashboardLandlordTenantsRoute: typeof DashboardLandlordTenantsRoute
  DashboardLandlordTransactionsRoute: typeof DashboardLandlordTransactionsRoute
  DashboardLandlordVisitsRoute: typeof DashboardLandlordVisitsRoute
  DashboardLandlordIndexRoute: typeof DashboardLandlordIndexRoute
}

const DashboardLandlordRouteChildren: DashboardLandlordRouteChildren = {
  DashboardLandlordAddPropertyRoute: DashboardLandlordAddPropertyRoute,
  DashboardLandlordAnalyticsRoute: DashboardLandlordAnalyticsRoute,
  DashboardLandlordMessagesRoute: DashboardLandlordMessagesRoute,
  DashboardLandlordPropertiesRoute: DashboardLandlordPropertiesRoute,
  DashboardLandlordReviewsRoute: DashboardLandlordReviewsRoute,
  DashboardLandlordSettingsRoute: DashboardLandlordSettingsRoute,
  DashboardLandlordTenantsRoute: DashboardLandlordTenantsRoute,
  DashboardLandlordTransactionsRoute: DashboardLandlordTransactionsRoute,
  DashboardLandlordVisitsRoute: DashboardLandlordVisitsRoute,
  DashboardLandlordIndexRoute: DashboardLandlordIndexRoute,
}

const DashboardLandlordRouteWithChildren =
  DashboardLandlordRoute._addFileChildren(DashboardLandlordRouteChildren)

interface DashboardTenantRouteChildren {
  DashboardTenantCompareRoute: typeof DashboardTenantCompareRoute
  DashboardTenantFavoritesRoute: typeof DashboardTenantFavoritesRoute
  DashboardTenantFeedRoute: typeof DashboardTenantFeedRoute
  DashboardTenantMapRoute: typeof DashboardTenantMapRoute
  DashboardTenantMessagesRoute: typeof DashboardTenantMessagesRoute
  DashboardTenantNotificationsRoute: typeof DashboardTenantNotificationsRoute
  DashboardTenantProfileRoute: typeof DashboardTenantProfileRoute
  DashboardTenantRentRoute: typeof DashboardTenantRentRoute
  DashboardTenantReviewsRoute: typeof DashboardTenantReviewsRoute
  DashboardTenantSearchRoute: typeof DashboardTenantSearchRoute
  DashboardTenantVisitsRoute: typeof DashboardTenantVisitsRoute
  DashboardTenantIndexRoute: typeof DashboardTenantIndexRoute
}

const DashboardTenantRouteChildren: DashboardTenantRouteChildren = {
  DashboardTenantCompareRoute: DashboardTenantCompareRoute,
  DashboardTenantFavoritesRoute: DashboardTenantFavoritesRoute,
  DashboardTenantFeedRoute: DashboardTenantFeedRoute,
  DashboardTenantMapRoute: DashboardTenantMapRoute,
  DashboardTenantMessagesRoute: DashboardTenantMessagesRoute,
  DashboardTenantNotificationsRoute: DashboardTenantNotificationsRoute,
  DashboardTenantProfileRoute: DashboardTenantProfileRoute,
  DashboardTenantRentRoute: DashboardTenantRentRoute,
  DashboardTenantReviewsRoute: DashboardTenantReviewsRoute,
  DashboardTenantSearchRoute: DashboardTenantSearchRoute,
  DashboardTenantVisitsRoute: DashboardTenantVisitsRoute,
  DashboardTenantIndexRoute: DashboardTenantIndexRoute,
}

const DashboardTenantRouteWithChildren = DashboardTenantRoute._addFileChildren(
  DashboardTenantRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  HelpRoute: HelpRoute,
  ListingsRoute: ListingsRoute,
  LoginRoute: LoginRoute,
  PressRoute: PressRoute,
  PrivacyRoute: PrivacyRoute,
  ReportRoute: ReportRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  DashboardAdminRoute: DashboardAdminRouteWithChildren,
  DashboardLandlordRoute: DashboardLandlordRouteWithChildren,
  DashboardTenantRoute: DashboardTenantRouteWithChildren,
  PropertyIdRoute: PropertyIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
